### ISSUE TITLE
A Forgotten Change

### ISSUE THREAD

**Issue by BadJacky** [xiebinbin/laravel-dogecloud#1]
https://github.com/xiebinbin/laravel-dogecloud/blob/64919ab90055e3696790c3586d41e1b4b7473c50/src/DogeCloudServiceProvider.php#L39

**Comment by BadJacky** [comment]
`class DogeCloudAdapter extends S3Adapter`
这个类没有被使用到，创建出来的意义是什么呢？是不是忘记在 Provider 中替换了？

**Comment by BadJacky** [comment]
@xiebinbin

**Comment by echo19981024** [comment]
之前是 直接继承的 S3Adapter
好像按照你说的是要 简洁很多
多谢多谢 已经提交更新了
